let addFoods = [
	{
		name:"面包秀",
		imgSrc:"./assets/images/f4.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:333,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'30g'},
			{name:'鸡蛋',weight:'40g'},
			{name:'生菜',weight:'70g'},
			{name:'生菜',weight:'70g'},
			{name:'生菜',weight:'70g'},
			{name:'生菜',weight:'70g'},
			{name:'生菜',weight:'70g'},
			{name:'培根',weight:'50g'},
			{name:'吐丝',weight:'25g'}
		],
		scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'33',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'17',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'81',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'12',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'43',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"草莓蓝莓派",
		imgSrc:"./assets/images/f5.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:133,
		discuss:224,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'26',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"西冷牛排",
		imgSrc:"./assets/images/f1.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:283,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'22',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'36',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"面包秀",
		imgSrc:"./assets/images/f1.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:633,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],
		scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'36',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"草莓蓝莓派",
		imgSrc:"./assets/images/f4.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:126,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],
		scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'36',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"西冷牛排",
		imgSrc:"./assets/images/f4.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:852,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],
		scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'36',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	},{
		name:"面包秀",
		imgSrc:"./assets/images/f4.png",
		id:'',
		detailSrc:'./assets/images/food1.png',
		pageView:133,
		discuss:124,//讨论
		foodMaterial:[
			{name:'小番茄',weight:'60g'},
			{name:'鸡蛋',weight:'50g'},
			{name:'生菜',weight:'20g'},
			{name:'培根',weight:'20g'},
			{name:'吐丝',weight:'25g'}
		],
		scaleData:[
  	 		{
  	 			unit:'g',
  	 			weight:'60',
  	 			scale:.11,
  	 			name:'热量'
  	 		},{
  	 			unit:'g',
  	 			weight:'40',
  	 			scale:.14,
  	 			name:'蛋白质'
  	 		},{
  	 			unit:'g',
  	 			weight:'29',
  	 			scale:.12,
  	 			name:'脂肪'
  	 		},{
  	 			unit:'g',
  	 			weight:'24',
  	 			scale:.14,
  	 			name:'碳水化合物'
  	 		},{
  	 			unit:'g',
  	 			weight:'30',
  	 			scale:.11,
  	 			name:'膳食纤维'
  	 		},{
  	 			unit:'g',
  	 			weight:'36',
  	 			scale:.12,
  	 			name:'微量元素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.16,
  	 			name:'维生素'
  	 		},{
  	 			unit:'g',
  	 			weight:'20',
  	 			scale:.1,
  	 			name:'其它'
  	 		}
	  	],
		steps:[
			'第一步',
			'第二步',
			'第三步',
			'第四步',
			'第五步'
		]
	}
];

export default addFoods;